export { default as Navbar } from './Navbar';
export { default as Welcome } from './Welcome';
export { default as Services } from './Services';
export { default as About } from './About';
export { default as Newsletter } from './Newsletter';
export { default as Review } from './Review';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as UserProfile } from './UserProfile';
